# Generated by Django 5.1.4 on 2024-12-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['firstname', 'other_name', 'surname']},
        ),
    ]
