# Generated by Django 5.0.7 on 2024-12-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0005_subject_classes"),
        ("students", "0003_alter_student_registration_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="current_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="corecode.studentclass",
            ),
        ),
    ]
