# Generated by Django 5.1.4 on 2024-12-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_current_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['firstname', 'other_name', 'surname']},
        ),
    ]
