# Generated by Django 5.1.4 on 2025-01-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
