# Generated by Django 5.1.4 on 2025-01-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
