# Generated by Django 5.0.7 on 2024-12-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0004_auto_20201124_0614"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="classes",
            field=models.ManyToManyField(
                related_name="subjects", to="corecode.studentclass"
            ),
        ),
    ]
