# Generated by Django 5.1.4 on 2024-12-14 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='corecode.studentclass'),
        ),
    ]
