# Generated by Django 5.0.7 on 2024-12-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0006_subjectclass"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="classes",
        ),
    ]
