# Generated by Django 5.1.4 on 2024-12-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_subject_student_class'),
        ('corecode', '0007_remove_subject_classes'),
    ]

    operations = [
    ]
