# Generated by Django 5.1.4 on 2024-12-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0008_merge_20241215_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student_class',
        ),
    ]
