# Generated by Django 5.1.4 on 2024-12-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0009_remove_subject_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos/', verbose_name='Logo Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
